url: https://nilstgmd.github.io/
baseurl: /tc-tangermuende

# Site settings
title: Tennisclub Tangerm端nde 93 e.V.
email: olaf.meder@rosier.de
description: "Willkommen im Tennisclub Tangerm端nde 93 e.V. Informieren Sie sich bei uns 端ber Tennistraining, Platzmiete und unsere Kinder- und Jugendarbeit."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: b81500
  secondary: 822519
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Postal address (add as many lines as necessary)
address:
  - line: Lange Fischer Str. 17
  - line: 39590 Tangerm端nde

# Build settings
markdown: kramdown
permalink: pretty
