url: https://nilstgmd.github.io/
baseurl: /tc-tangermuende

# Site settings
title: Tennisclub Tangermünde 93 e.V.
email: olaf.meder@rosier.de
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: b81500
  secondary: 822519
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Postal address (add as many lines as necessary)
address:
  - line: Lange Fischer Str. 17
  - line: 39590 Tangermünde

# Build settings
markdown: kramdown
permalink: pretty
